apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
  labels:
    app: sentinel
    component: api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: sentinel
    component: api
    release: {{ .Release.Name }}
